[FEATURE] Add tags for events
Club-Alpin-Annecy/collectives pull request #383
Opened 2020-12-16 23:50 UTC by jnguiot

https://trello.com/c/jBXUPPst/161-picto-sur-une-collective-mobilit%C3%A9-douce-cpm-etc

2020-12-17 20:18 UTC, gdaviet requested changes
L'UX me parait bien!

Par contre je déconseille fortement d'utiliser une Enum pour la liste des tags, ca va demander une migration à chaque mise à jour et sémantiquement ca ne me parait pas correct. A mon avis, les Enum sont adaptées lorsqu'on a un ensemble bien définit et que la logique des routes dépend de la valeur (par ex les roles, ont ne vas pas exécuter le même code selon le cas).
Ici il s'agit juste d'une liste de données, donc un tableau dans le `config.py` me paraitrait beaucoup plus adapté (ou une table bd, mais ca ne vaut surement pas ke coup)

2020-12-17 20:18 UTC, gdaviet commented on collectives/models/event.py
> +    tag_ref = db.relationship(
Mineur, mais à mon avis pour plus de clarté le nom de variable devrait être au pluriel (`tag_refs`, ou `tag_ref_list`)

2020-12-17 20:18 UTC, gdaviet commented on collectives/routes/event.py
> +        event.tag_ref.remove(tag)
Je suggérerais `event.tag_ref.clear()`

2020-12-17 22:07 UTC, jnguiot commented
> Par contre je déconseille fortement d'utiliser une Enum pour la liste des tags, ca va demander une migration à chaque mise à jour et sémantiquement ca ne me parait pas correct. A mon avis, les Enum sont adaptées lorsqu'on a un ensemble bien défini et que la logique des routes dépend de la valeur (par ex les roles, ont ne vas pas exécuter le même code selon le cas).

En effet, je comprends ton point de vue: faire des enum rends la liste des tags très "statique". Cependant, cette liste ne changera que par modification du code: en effet, si on doit rajouter un tag, on devra forcément rajouter un logo, donc faire un commit. Est-ce que ca ne rendrait pas l'utilisation de l'Enum plus acceptable? J'ai quand même passé à l'utilisation d'un dict dans config.py, car ca me parait plus simple que les Enum.

Est-ce que les modifications te conviennent?

2020-12-17 22:12 UTC, jnguiot commented on collectives/models/event.py
> +    tag_ref = db.relationship(
done

2020-12-17 22:12 UTC, jnguiot commented on collectives/routes/event.py
> +        event.tag_ref.remove(tag)
super!

2020-12-18 07:39 UTC, gdaviet approved these changes

2020-12-18 07:41 UTC, gdaviet commented
> 
> En effet, je comprends ton point de vue: faire des enum rends la liste des tags très "statique". Cependant, cette liste ne changera que par modification du code: en effet, si on doit rajouter un tag, on devra forcément rajouter un logo, donc faire un commit. Est-ce que ca ne rendrait pas l'utilisation de l'Enum plus acceptable? J'ai quand même passé à l'utilisation d'un dict dans config.py, car ca me parait plus simple que les Enum.
> 
> Est-ce que les modifications te conviennent?

Oui nickel avec le dict ! Faire un commit c'est toujours moins angoissant qu'une migration :)

2020-12-18 16:17 UTC, merged