[FIX] Fix front page css for mobile
Club-Alpin-Annecy/collectives pull request #423
Opened 2021-05-12 20:10 UTC by jnguiot

Minor tweaks to have a more readable index page on mobile
![Screenshot_2021-05-12 Collectives Liste](https://user-images.githubusercontent.com/45011516/118037981-d5392a80-b36e-11eb-87d0-58e771ca159f.png)

2021-05-12 20:32 UTC, gdaviet approved these changes
Juste une remarque, la photo disparait au format mobile (ok) mais également au  format tablette alors qu'il pourrait y avoir la place:

![Capture d’écran 2021-05-13 à 22 25 58](https://user-images.githubusercontent.com/57617656/118040219-9789d100-b371-11eb-9766-4489f5d6ba71.png)

Après ce n'est pas vraiment un format prioritaire.
Sinon par curiosité, pourquoi échanger la place des icones d'activité/titre?

2021-05-13 18:29 UTC, jnguiot commented
> Sinon par curiosité, pourquoi échanger la place des icones d'activité/titre?

Le float marchait mal sur le coté gauche donc je l'ai mis sur le droit, où il y a souvent plus de place sur les écrans étroits.

> Juste une remarque, la photo disparait au format mobile (ok) mais également au format tablette alors qu'il pourrait y avoir la place:

Vu. En effet, on passe en mode "mobile" quand l'écran est inférieur à 1023px, alors qu'il reste assez de place. Je vais le passer à 700px. @gregone me contredira si c'est pas ce qu'il faut faire ;)

2021-05-14 17:14 UTC, gregone commented
@gdaviet @jnguiot Pour l'image en format tablette: il y a l'air d'avoir la place quand on a des titres de collectives qui font 8 caractères, mais quand tu vois les vrais titres, ce n'est pas une bonne idée tant qu'on a pas revu tout le reste du composant de la collective: 

exemple avec des vrais titres:

<img width="922" alt="Screenshot 2021-05-14 at 19 12 34" src="https://user-images.githubusercontent.com/1416421/118305654-8c0ce600-b4e8-11eb-8e43-bf8fac7fe2ef.png">

2021-05-14 17:23 UTC, jnguiot commented
Ok, je reste à 1024 alors

2021-05-14 17:26 UTC, merged

2021-05-14 17:28 UTC, gregone requested changes
La table utilise flex box, la tu passe les elements en `display: block` pour faire marcher ton float, que l'on devrait éviter aussi. Je préférais refaire le css pour la partie `.row`

2021-05-14 17:28 UTC, gregone commented on collectives/static/css/legacy/event/event-details.scss
> +        display: block;
```suggestion
```