Parent event (écoles du pauvre)
Club-Alpin-Annecy/collectives pull request #440
Opened 2021-06-13 18:32 UTC by gdaviet

Ce changeset introduit la fonctionnalité de limiter les inscriptions à une collective aux participants d'une collective précédente.

Pour l'instant il n'y a pas de concept d'école, car je me suis dit  que cette fonctionnalité pouvait aussi être utile dans d'autres cas: par exemple une collective a été annulé pour cause de météo, l'encadrant en propose une nouvelle ultérieurement mais souhaite donner les priorité aux inscrit de la collective originale.

Je pense que ca peut  déjà répondre a plusieurs besoins, éventuellement dans un premier temps on pourrait simplement avoir un tag "école" en plus pour distonguer les collectives d'inscription aux écoles. Dites moi ce que vous en pensez

2021-06-16 21:57 UTC, jnguiot requested changes
J'ai fait quelques propositions de reformulation pour que ce soit plus simple à comprendre. 
Même si ce sont des écoles light, les appellerais bien école dans les IHM. Le but est de présenter ça de façon plus simple à appréhender qu'une simple liaison entre les events. Mais il faudrait avoir le retour de françois.

2021-06-16 21:57 UTC, jnguiot commented on collectives/templates/editevent.html
> +        setupAutoComplete(
A noter que l'autocomplete ne fonctionne qu'à partir de 2 caractères... Pour les collectives avec un id à un chiffre, il faut précéder d'un zéro.

2021-06-17 09:26 UTC, gdaviet commented on collectives/templates/editevent.html
> +        setupAutoComplete(
C'est vrai, mais je me disais que ca ne devrait pas être un problème en prod, les event à un chiffre sont passés depuis bien longtemps

2021-06-17 09:28 UTC, gdaviet commented on collectives/models/event.py
> +          - they have no current registration with this event.
Les pronoms genrés sont assez mal vus en anglais de nos jours, la forme neutre est généralement préférée même au singulier

2021-06-17 10:10 UTC, gdaviet commented on collectives/api/event.py
> +            condition = Event.title.ilike(f"%{q}%")
`isdigit` ne fait pas exactement ce qu'on veut: https://www.w3schools.com/python/ref_string_isdigit.asp
```python
>>> a="²"
>>> a.isdigit()
True
>>> int(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '²'
```
 
Je trouvais plus intuitif de chercher le chiffre dans le titre également au cas où

2021-06-17 11:17 UTC, gdaviet commented on collectives/models/event.py
> +        return self.parent_event is None or self.parent_event.is_registered_with_status(
Bon finalement c'est quand même trop long pour tenir sur une ligne, mais plus lisible au moins!

2021-06-29 20:02 UTC, gdaviet commented
> J'ai fait quelques propositions de reformulation pour que ce soit plus simple à comprendre.
> Même si ce sont des écoles light, les appellerais bien école dans les IHM. Le but est de présenter ça de façon plus simple à appréhender qu'une simple liaison entre les events. Mais il faudrait avoir le retour de françois.

Du coup après discussion avec Francois je vais merger cette PR, et on ajoutera les écoles dans les types d'événements (https://trello.com/c/6TCFEjnD/244-distinguer-les-collectives-des-formations-des-ventes-en-ligne-etc)

2021-06-29 20:05 UTC, merged