Allow registration after license expires
Club-Alpin-Annecy/collectives pull request #448
Opened 2021-07-24 20:43 UTC by gdaviet

Carte trello https://trello.com/c/6RPxZ6iC/245-pouvoir-sinscrire-%C3%A0-une-collective-alors-que-je-nai-pas-encore-renouvel%C3%A9-ma-licence

(Cette PR est intéressée, je viens de rencontrer ce problème)

2021-07-24 20:58 UTC, jnguiot requested changes
Je pense qu'il manque cette partie de la carte:

> L'idée est cette carte est d'autoriser jusqu'au 30 septembre 23h59 les inscriptions à une collective après le 1er octobre alors que la licence n'est pas renouvelée. L'inscription aura alors un statut "en attente de renouvellement de licence" et comptera comme une inscription.

Sinon, ca me parait bon.

2021-07-24 20:58 UTC, jnguiot commented on collectives/templates/event.html
> +            Si vous venez de renouveller votre licence, merci de resynchronizer vos informations FFCAM dans votre <a href="{{ url_for('profile.show_user', user_id=current_user.id)}}">profil utilisate
Je pense qu'on pourrait mettre le bouton de resynchronisation du compte ici, plutôt que de renvoyer vers le profil

2021-07-25 06:30 UTC, gdaviet commented
> Je pense qu'il manque cette partie de la carte:
> 
> > L'idée est cette carte est d'autoriser jusqu'au 30 septembre 23h59 les inscriptions à une collective après le 1er octobre alors que la licence n'est pas renouvelée. L'inscription aura alors un statut "en attente de renouvellement de licence" et comptera comme une inscription.

@jnguiot i je comprends bien ta question c'est déjà indirectement le cas: après le 30 septembre 23h59 l'utilisateur sera automatiquement déloggué du site (cf `load_user` in `auth.py`), donc il ne pourra de toute façon pas s'inscrire.

2021-07-25 06:31 UTC, gdaviet commented on collectives/templates/event.html
> +            Si vous venez de renouveller votre licence, merci de resynchronizer vos informations FFCAM dans votre <a href="{{ url_for('profile.show_user', user_id=current_user.id)}}">profil utilisate
Oui j'hésitais aussi, je me disais que ca alourdissait la page event, mais pourquoi pas

2021-07-25 07:52 UTC, jnguiot commented
> @jnguiot si je comprends bien ta question c'est déjà indirectement le cas: après le 30 septembre 23h59 l'utilisateur sera automatiquement déloggué du site (cf `load_user` in `auth.py`), donc il ne pourra de toute façon pas s'inscrire.

Ah, en effet, bien vu :)

2021-07-25 07:53 UTC, jnguiot approved these changes

2021-07-25 07:54 UTC, merged