[FEATURE] Add waiting list
Club-Alpin-Annecy/collectives pull request #497
Opened 2022-01-27 22:37 UTC by jnguiot

Ajout d'un système de liste d'attente.
https://trello.com/c/xzqs6BiX/49-g%C3%A9rer-une-liste-dattente
Je n'ai pas fait le système de vérification d'inscription unique, car je pense que ça doit être discuté plus largement (cf notre discussion de lundi)

2022-02-02 07:06 UTC, gdaviet requested changes
Joli travail !

 - Le request change c'est surtout pour le coup du has_free_slots() vs has_free_online_slots(), AMA on  ne devrait utiliser que le second
 - Question: Que se  passe-t-il si l'encadrant augmente le nombre de places de la collective ? Faudrait-il d'abord vider la liste d'attente ?

2022-02-02 12:46 UTC, jnguiot commented on collectives/models/registration.py
> +            cls.Waiting: [cls.Rejected, re_register_status],
Le passage de Waiting à Active est autorisé par `re_register_status`, non?

2022-02-02 20:11 UTC, jnguiot commented on collectives/templates/partials/event/self_register.html
> +{% if event.requires_payment() and not waiting_list %}
Je vais faire le https://trello.com/c/5qdqybDf/256-afficher-les-tarifs-dune-collective-pour-lencadrant-et-ladh%C3%A9rent-lorsque-les-inscriptions-ne-sont-pas-ouvertes dans la foulée

2022-02-02 20:14 UTC, jnguiot commented
> Question: Que se passe-t-il si l'encadrant augmente le nombre de places de la collective ? Faudrait-il d'abord vider la liste d'attente ?

Pour moi, oui: en cas d'augmentation du nombre de place, la file d'attente doit être "consommée". En gros, il faut je fasse un `update_waiting_list()` après la modification d'un event.

2022-02-03 12:49 UTC, gdaviet commented on collectives/models/registration.py
> +            cls.Waiting: [cls.Rejected, re_register_status],
Ah oui effectivement, j'avais zappé ça !

2022-02-03 12:53 UTC, gdaviet commented on collectives/templates/partials/event/self_register.html
> +{% if event.requires_payment() and not waiting_list %}
Justement cette partie de la carte est déjà implémentée, je pense qu'on peut utiliser le même code.
La partie qui manque c'est la prévisualisation de tous les tarifs pour les encadrants/modérateurs, mais ça je pense que ca se passe plus sur la page d'édition des tarifs (et c'est un peu complexe niveau UI car il faut prévoir toutes les combinaisons de type de licence, encadrant ou non, etc)

2022-02-03 12:58 UTC, jnguiot commented on collectives/templates/partials/event/self_register.html
> +{% if event.requires_payment() and not waiting_list %}
Elle est déjà implémentée?
To be honest, je suis en train de travailler dessus pour afficher tous les tarifs tout le temps en bas de la page (même s'ils ne sont pas lié à la catégorie de l'utilisateur)

2022-02-03 13:03 UTC, gdaviet commented on collectives/templates/partials/event/self_register.html
> +{% if event.requires_payment() and not waiting_list %}
Mais effectivement on peut aussi inclure un tableau récapitulatif de tous les tarifs "pour information", même si ce sera différent de ce que les utilisateurs verront au moment de payer

2022-02-03 22:19 UTC, jnguiot commented
@gdaviet Est-ce que tu peux me relire la table des prix stp?

2022-02-04 19:46 UTC, gdaviet reviewed
Je suis un peu mitigé sur la table, je ne sais pas trop le nombre de tarifs crées par les encadrants en vrai. Là sur mes tests la table ca fait vraiment massif et il est assez difficile de se rendre compte quels tarifs seront vraiment proposés, mais il faut dire que c'est une configuration vraiment compliquée (et que la table contient des tarifs a priori d'autres événements), donc je pense que ce sera moins le cas en vrai.
Je serais quand même personnellement pour passer la table en dessous de la zone Administration, et ajouter la preview des tarifs personallisée pour la waiting list.

2022-02-04 19:46 UTC, gdaviet commented on collectives/api/payment.py
> +        .filter(PaymentItem.event_id == event_id)
Il manque un `ItemPrice.item_id == PaymentItem.id` ou quelque chose du genre non? J'ai l'impression que ca m'affiche tous les tarifs, pas juste ceux de la collective

2022-02-04 19:46 UTC, gdaviet commented on collectives/templates/partials/event/payment_item_list.html
> +  <script type="text/javascript" src="{{ url_for('static', filename='js/event/payment_item_list.js') }}"></script>
Préférence personnelle pour passer l'event_id comme argument d'une fonctioon createTable() plutot que d'introduire une variable globale

2022-03-27 11:33 UTC, fberu commented on collectives/templates/editevent.html
> +    <div class="controls">
Réflexion: ne devrions-nous pas commencer à avoir un panneau avec les données optionnels ? Pas sûr que grand monde utilise cette option

2022-03-27 12:49 UTC, fberu commented on collectives/templates/event.html
> +
Lorsque la liste des inscrits est complètes et qu'une liste d'attente est possible, il faudrait afficher des messages expliquant cette liste d'attente:

`Le nombre maximum d'inscrits par internet a été atteint.` -> `Le nombre maximum d'inscrits par internet a été atteint. Vous pouvez cependant vous inscrire sur liste d'attente`

Dans ce cas là, le bouton `s'inscrire` devrait plus être `s'incrire sur liste d'attente` afin qu'il n'y ait aucune confusion

2022-03-27 12:52 UTC, fberu commented on collectives/email_templates.py
> +def send_update_waiting_list_notification(registration):
Tip top!

2022-03-27 13:12 UTC, fberu commented
Super taf!
J'ai mis des commentaires sur des détails.

Après des tests et utilisation, se posent plusieurs questions:

* effectivement il y a le point d'inscription unique. Pour moi aucun soucis pour qu'une personne s'inscrire sur plusieurs listes d'attente le même jour MAIS que se passe-t-il s'il retrouve inscrit (pour de vrais) sur 2 collectives le même jour ? Il faudrait donc résoudre #427 et mettre en place la mécanique: si inscrit sur plusieurs d'attente, dès qu'il sort d'une, alors il sort de toute
* être averti par mail est top. Malheureusement les encadrants ont constaté que des gens s'auto désinscrivent le soir pour le lendemain (des fois à 2h du mat pour un départ à 7h). Dans ce cas là, celui sur liste d'attente est prévenu tardivement qu'il est inscrit et a de grandes chances de ne pas voir la notification. Et du coup l'encadrant grognera le matin au parking parce qu'il n'est pas là

Je pense qu'il y a aussi d'autres corner cases, compliqué à voir sans utilisation.

Ma proposition:

* fixer #427 
* lancer cette fonctionnalité en mode "beta" ce printemps / été afin d'avoir un max de feedbacks pour cet hiver: en effet c'est surtout le ski de rando qui a besoin de cette fonctionnalité

2022-03-27 13:13 UTC, fberu commented
J'ai oublié: il serait bien d'avoir sur son profil les collectives sur lesquelles un adhérent est en liste d'attente

2022-05-04 21:01 UTC, jnguiot commented on collectives/templates/event.html
> +
> Le nombre maximum d'inscrits par internet a été atteint. -> Le nombre maximum d'inscrits par internet a été atteint. Vous pouvez cependant vous inscrire sur liste d'attente

Ca me parait assez explicite pourtant, vu que la liste d'attente est affichée juste en dessous :thinking:

> Dans ce cas là, le bouton s'inscrire devrait plus être s'incrire sur liste d'attente afin qu'il n'y ait aucune confusion

Je vais rajouter ça, pour être sur que les adhérents voient que c'est une liste d'attente

2022-05-04 21:06 UTC, jnguiot commented on collectives/templates/editevent.html
> +    <div class="controls">
Pourquoi pas, à voir avec @gregone . Cependant, j'aime bien afficher toutes les options quand même: ca permet aux encadrants de voir toutes les options proposées.
Je pense rester comme ça pour cette PR, mais on pourra modifier par la suite.

2022-05-05 18:12 UTC, jnguiot commented on collectives/api/payment.py
> +        .filter(PaymentItem.event_id == event_id)
Corrigé

2022-05-05 18:12 UTC, jnguiot commented on collectives/templates/partials/event/payment_item_list.html
> +  <script type="text/javascript" src="{{ url_for('static', filename='js/event/payment_item_list.js') }}"></script>
J'ai fait sauter cette partie

2022-05-05 18:25 UTC, jnguiot commented
> J'ai oublié: il serait bien d'avoir sur son profil les collectives sur lesquelles un adhérent est en liste d'attente

vu

> Je suis un peu mitigé sur la table, je ne sais pas trop le nombre de tarifs crées par les encadrants en vrai. Là sur mes tests la table ca fait vraiment massif et il est assez difficile de se rendre compte quels tarifs seront vraiment proposés, mais il faut dire que c'est une configuration vraiment compliquée (et que la table contient des tarifs a priori d'autres événements), donc je pense que ce sera moins le cas en vrai. Et peut être que juste diminuer la taille de la police suffirait. On peut toujours merger et voir à l'usage sur test.collectives.

J'ai fait une table moins massive

> Je pense qu'il y a aussi d'autres corner cases, compliqué à voir sans utilisation.
> lancer cette fonctionnalité en mode "beta" ce printemps / été afin d'avoir un max de feedbacks pour cet hiver: en effet c'est surtout le ski de rando qui a besoin de cette fonctionnalité

En effet, il faut lancer et voir ce que ca donne.

2022-05-05 18:44 UTC, merged