[FIX] #428
Club-Alpin-Annecy/collectives pull request #505
Opened 2022-03-14 23:26 UTC by hug0be

Affichage d'un message d'erreur lorsque l'encadrant tente d'encadrer plusieurs activités en même temps
Fonctionne aussi pour l'édition de collective
Suggestion : Est ce que je devrais mettre la méthode `date_intersect` dans le fichier `utils/time.py` ?
Suggestion 2 : Je ne comprends pas pourquoi la table `event_leaders` n'est pas une classe modèle ? Il sera pertinent d'en faire une classe pour y ajouter des méthodes, mais surtout pour simplifier les requêtes sql !

2022-03-16 17:21 UTC, shaiton commented
attention, parfois en tant que responsable d’activité ça reste nécessaire pour l’organisation d’une collective.
Dans le cas ou l’encadrant ne sache pas utiliser le site des collective (ou que ce soit compliqué ) -> c’est temporaire le temps qu’on l’inscrive en organisateur
Mais aussi dans le cas où l’encadrant est coencadrant et qu’on est sur un événement de plus grande empleur avec deux collectives.
dans le passé j’ai également organisé des collectives avec pro (guide) et coencadrant (non encadrant) -> aucun n’avait les accès pour créer une collective.

2022-03-16 17:24 UTC, shaiton requested changes
au moins pour la typo.

2022-03-16 17:24 UTC, shaiton commented on collectives/routes/event.py
> +        flash("Vous encadrer déjà une activité à cette date", "error")
*encadrez*

2022-03-16 17:24 UTC, shaiton commented on collectives/routes/event.py
> +        flash("Vous encadrer déjà une activité à cette date", "error")
comme dit à côté, le « error » ne convient pas à tous les usages. @fberu je n’ai pas vu la description de la tâche et si tu as bien géré tous les cas, mais en cas d’intégration il faudra prévenir les bons usages du coup. (en tout cas ça fiabilisera les stats)

2022-03-16 18:02 UTC, gdaviet reviewed
Ces changements (enfin le ticket, pas le code lui même!) ne me semblent pas judicieux, comme mentionné dans #427 on est pas très précis sur les dates de début et de fin d'événements, ca risque de poser plus de problèmes que cela n'en résout.

Il y a d'autres cas comme les WEI/camps ou les utilisateurs s'inscrivent à la fois à la sortie générale et à des sorties particulières, il y a forcément un overlap (bon là on pourrait fiare le lien avec le parent_id). Mais on va trouver plein de cas particuliers du style, il faudrait qu';on réfléchisse vraiment plus à ces tickets avant de les aborder

Je vais enlever le badge "good first issue"


Sinon pour la question sur event_leaders: il n'y a pas de métadonnées associées à cette relation, donc pas besoin de modèles spécifique. SQLAlchemy fournit des outils pour simplifiers les requêtes, cf mon commentaire.
(Enfin cela dit maintenant on a le concept d'encadrants "responsable" qui aurait pu être associé, mais on avait pas prévu le coup au début)

2022-03-21 20:56 UTC, fberu commented
Pour répondre à toutes vos points.

De manière globale, j'émets ce besoin car par manque de connaissance du site ou par simplicité ou par manque de délégation, les responsables et/ou encadrants créent des collectives à tout va. Du coup, parmis les effets négatifs:

* les encadrants ne sont pas autonomes, ie ne savent pas se servir du site
* nous pouvons nous retrouver avec une collective dans les Aravis, une dans les Bauges mais avec le même encadrant (légalement ce n'est pas top)
* nous pourrions imaginer des améliorations ou évolutions mais comme les encadrants "bidouillent", on ne peut pas les voir

Pour répondre plus précisément
@shaiton 

> attention, parfois en tant que responsable d’activité ça reste nécessaire pour l’organisation d’une collective. Dans le cas ou l’encadrant ne sache pas utiliser le site des collective (ou que ce soit compliqué ) -> c’est temporaire le temps qu’on l’inscrive en organisateur
En tant que responsable d'activité, tu peux créer / modifier / supprimer une collective pour n'importe quel encadrant

> Mais aussi dans le cas où l’encadrant est coencadrant et qu’on est sur un événement de plus grande empleur avec deux collectives.
Rien ne t'empêche de créer une collective à 50 personnes. Si 2 collectives, alors 2 groupes distincts, et un encadrant par collective

> dans le passé j’ai également organisé des collectives avec pro (guide) et coencadrant (non encadrant) -> aucun n’avait les accès pour créer une collective.

Il est possible de créer des comptes pour les pro qui ne sont pas adhérents au club (on l'a pas pour l'accès libre SAE et cours de cet hiver).
Un co-encadrant est forcément un encadrant, il doit être connu. Si c'est toi qui organise, alors c'est toi l'encadrant ;)


@gdaviet 

> Ces changements (enfin le ticket, pas le code lui même!) ne me semblent pas judicieux, comme mentionné dans #427 on est pas très précis sur les dates de début et de fin d'événements, ca risque de poser plus de problèmes que cela n'en résout.

PR posée apparemment ;)

> Il y a d'autres cas comme les WEI/camps ou les utilisateurs s'inscrivent à la fois à la sortie générale et à des sorties particulières, il y a forcément un overlap (bon là on pourrait fiare le lien avec le parent_id). Mais on va trouver plein de cas particuliers du style, il faudrait qu';on réfléchisse vraiment plus à ces tickets avant de les aborder

Vrai... mais c'était avant ;) En effet plus trop maintenant avec les event types Collective vs Inscription. Les WEI / camp sont de type inscription et les sorties particulières sont des collectives. Rien ne doit interdire le chevauchement inscripton vs collectives. Seules les collectives sont concernées.

Le truc c'est que pas plus tard que la semaine dernière une personne s'est inscrite sur 2 collectives ayant lieu au même moment: ce n'est pas fair, cela pique une place à qq'un et le matin l'un des 2 encadrants aura une personne en moins.

2022-03-22 19:11 UTC, gdaviet commented
> 
> Vrai... mais c'était avant ;) En effet plus trop maintenant avec les event types Collective vs Inscription. Les WEI / camp sont de type inscription et les sorties particulières sont des collectives. Rien ne doit interdire le chevauchement inscripton vs collectives. Seules les collectives sont concernées.
> 

Oui, effectivement si on limite la restriction aux collectives "Collectives" ca limite pas mal les risques... mais ce n'est pas mentionné explicitement dans le ticket, et du coup pas dans le code de cette PR non plus. Du coup ca rejoint ce que je disais, il faudrait être sûrs d'avoir bien regardé  les cas particuliers (si il y en a d'autres) et spécifié les tickets avant d'implémenter cette feature.

2022-03-23 08:22 UTC, shaiton commented
d’accord pour les différentes remarques.
Il apparait donc important de débuter une documentation fonctionnelle (et
que les changements de code y contribuent)
perso j’ai décroché rapidement quand j’ai vu toutes les évolutions sans
comprendre en profondeur les impact fonctionnels.

Et mes remarques c’était effectivement pour être sur que ces périmètres
étaient couverts. On a beaucoup d’encadrants qui ne savent pas créer une
collective. Alors oui la distinction inscription/collective est importante
mais complexe.

Je ne dis pas qu’il n’y a pas de doc, mais c’est plus une documentation
développeur, non ?
Ou alors un guide de démarrage, mais pas une documentation exhaustive des
différentes fonctionnalitées.




On Tue, Mar 22, 2022 at 8:12 PM gdaviet ***@***.***> wrote:

> Vrai... mais c'était avant ;) En effet plus trop maintenant avec les event
> types Collective vs Inscription. Les WEI / camp sont de type inscription et
> les sorties particulières sont des collectives. Rien ne doit interdire le
> chevauchement inscripton vs collectives. Seules les collectives sont
> concernées.
>
> Oui, effectivement si on limite la restriction aux collectives
> "Collectives" ca limite pas mal les risques... mais ce n'est pas mentionné
> explicitement dans le ticket, et du coup pas dans le code de cette PR non
> plus. Du coup ca rejoint ce que je disais, il faudrait être sûrs d'avoir
> bien regardé les cas particuliers (si il y en a d'autres) et spécifié les
> tickets avant d'implémenter cette feature.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Club-Alpin-Annecy/collectives/pull/505#issuecomment-1075530870>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADMXP77IYT6S47YUWRINTDVBILQPANCNFSM5QXAMSHQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-24 16:55 UTC, gdaviet commented
Merci @hug0be pour les changements ! J'ai rebasé la PR (mais du coup j'ai du changer de branche car pas accès à ton fork). La suite ici #519

2022-07-24 16:55 UTC, closed without merging