Attestation benevole
Club-Alpin-Annecy/collectives pull request #521
Opened 2022-07-30 19:41 UTC by SnowViet

@jnguiot Voilà le PR !
J'ai fini par corrigé le problème d'encodage avant le PR ;)
J'ai juste le ".vscode/launch.json" dans le PR, je dois l'enlever ?

2022-07-30 19:46 UTC, jnguiot commented
En effet, j'ai rajouté le .vscode dans un commit précédent: a48d82f316edba680026b87f78b20ad6cc3ebd1f

2022-07-30 20:34 UTC, jnguiot requested changes
Merci beaucoup pour cette PR! Dans l'ensemble, ca marche plutôt bien: et le pip choisi a l'air robuste.
- Le nom d'au moins un commit dans contenir [FEATURE] cf https://github.com/Club-Alpin-Annecy/collectives/blob/master/CODING.md . C'est pour que ce soit détecté par le système de release note.
- A noter que les fichiers images ne doivent pas être dans templates, mais dans `collectives/static` , dans notre cas, dans `collectives/static/caf` . 
- Je mettrais bien un nom plus générique pour le dossier `attestation_benevole`, comme `document`

2022-07-30 20:34 UTC, jnguiot commented on collectives/routes/profile.py
> +        attachment_filename=str(
Pour générer des chaines de caractères, je te conseille d'utiliser des[ f-strings](https://he-arc.github.io/livre-python/fstrings/index.html) . eg:
```
attachment_filename= f"Attestation Benevole - {current_user.full_name()}.pdf"
```
Cependant, je ne pense pas qu'il soit utile de mettre le nom de la personne dans le nom du fichier. On peut juste mettre "Attestation Benevole CAF Annecy.pdf" tout le temps! 😁

2022-07-30 20:34 UTC, jnguiot commented on collectives/templates/attestation_benevole/attestation_benevole.html
> +		<img src="./collectives/templates/attestation_benevole/footer_attestation_benevole.png" />
Idem que pour le header

2022-07-30 20:34 UTC, jnguiot commented on collectives/templates/attestation_benevole/attestation_benevole.html
> +		<img src="./collectives/templates/attestation_benevole/header_attestation_benevole.png" />
Je te conseille de faire les liens avec url_for.
Exemple: https://github.com/Club-Alpin-Annecy/collectives/blob/a48d82f316edba680026b87f78b20ad6cc3ebd1f/collectives/templates/base.html#L60
A noter que les fichiers doivent être dans static pour que ça marche

2022-07-30 20:34 UTC, jnguiot commented on collectives/templates/attestation_benevole/attestation_benevole.html
> +		<h2>Je soussigné, {{ president.full_name() }}, Président du Club l’Alpin d’Annecy,</h2>
Je laisserais bien en `<p>` pour que ça fasse la même taille que le reste du texte

2022-07-30 20:34 UTC, jnguiot commented on collectives/templates/attestation_benevole/attestation_benevole.html
> +				margin-bottom:50px;
Le texte est écrit en assez petit, je pense qu'on peut mettre un `font-size: 14px;`

2022-07-31 20:43 UTC, romaind8r commented
Yes yes yes je kiffe cette PR !! 😀

Romain Desbrest

Président 
Club Alpin Français Annecy
   
+33 6 50 17 45 47
 
***@***.***


Le 30 juil. 2022 à 21:41, SnowViet ***@***.***> a écrit :

@jnguiot <https://github.com/jnguiot> Voilà le PR !
J'ai fini par corrigé le problème d'encodage avant le PR ;)
J'ai juste le ".vscode/launch.json" dans le PR, je dois l'enlever ?

You can view, comment on, or merge this pull request online at:

  https://github.com/Club-Alpin-Annecy/collectives/pull/521 <https://github.com/Club-Alpin-Annecy/collectives/pull/521>
Commit Summary

391935f <https://github.com/Club-Alpin-Annecy/collectives/pull/521/commits/391935f28df506ac15d23c8aad918ba5175ae16a> Test PyPDF2
545c2ba <https://github.com/Club-Alpin-Annecy/collectives/pull/521/commits/545c2ba3afe9988b58b16c28db41693f7750eb4a> Génération du PDF avec xhtml2pdf
c40e2b4 <https://github.com/Club-Alpin-Annecy/collectives/pull/521/commits/c40e2b48ea6629d5d636d938190dda0a26e2fc1e> Correction pylint
File Changes (8 files <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files>)
A .vscode/launch.json <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945> (24)
M collectives/routes/profile.py <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-ad388419e57333111f674e65f2bfecf7cc1f92f55605cc584b5814c8459f62a6> (58)
A collectives/static/img/icon/ionicon/md-file-document.svg <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-2cb295c1e86340b2b3f31ef81c1c9cba756a7391c81e4af313f00ab08faa8028> (1)
A collectives/templates/attestation_benevole/attestation_benevole.html <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-1ed1ded50ce2cc3d8188be8010f4ab29db3bf15b6416f578f87afd3da382af72> (54)
A collectives/templates/attestation_benevole/footer_attestation_benevole.png <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-e64b8fb235cd00818943f5fb448a49da4c81e510094bbc3607420f7570859eeb> (0)
A collectives/templates/attestation_benevole/header_attestation_benevole.png <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-2ac5867961f227ed7345be1c5de188267339db5d1b2ba9e12730a46542d3cd4c> (0)
M collectives/templates/profile.html <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-3c8a0fdabff811567613127dcb3b1069719e41be6d7ccc88c22165d6e9a77b43> (4)
M requirements.txt <https://github.com/Club-Alpin-Annecy/collectives/pull/521/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552> (1)
Patch Links:

https://github.com/Club-Alpin-Annecy/collectives/pull/521.patch <https://github.com/Club-Alpin-Annecy/collectives/pull/521.patch>
https://github.com/Club-Alpin-Annecy/collectives/pull/521.diff <https://github.com/Club-Alpin-Annecy/collectives/pull/521.diff>
—
Reply to this email directly, view it on GitHub <https://github.com/Club-Alpin-Annecy/collectives/pull/521>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACR63N5S3QG6UKMBGGWAPDLVWWAPDANCNFSM55DWHJEA>.
You are receiving this because you are subscribed to this thread.

2022-08-01 09:52 UTC, SnowViet commented on collectives/templates/attestation_benevole/attestation_benevole.html
> +		<img src="./collectives/templates/attestation_benevole/header_attestation_benevole.png" />
{{ url_for('static', filename='caf/header_attestation_benevole.png') }} retourne "/static/caf/header_attestation_benevole.png"
et non "./collectives/static/caf/header_attestation_benevole.png"
Je peux "bidouiller" en ajoutant "./collectives" manuellement éventuellement.

2022-08-01 09:57 UTC, SnowViet commented
@jnguiot, J'ai fait les changements. Juste pour l'utilisation de "url_for", j'ai mis le "header" avec et le footer sans. Dis moi ce qui te semble le mieux.

2022-08-02 18:21 UTC, jnguiot commented on collectives/templates/attestation_benevole/attestation_benevole.html
> +		<img src="./collectives/templates/attestation_benevole/header_attestation_benevole.png" />
En fait, le url_for est très pratique quand l'image est affchée dans un navigateur. Pas besoin de rajouter ./collectives manuellement, tout est fait automatiquement.

Sauf que je me suis trompé... La page n'est pas affichée dans un navigateur, mais généré dans le pdf. Donc finalement, je te conseille d'enlever le url_for, et de mettre le chemin relatif depuis la base du projet, comme tu avais fait avant :) . Désolé pour le chaud et le froid :)

2022-08-02 18:23 UTC, jnguiot approved these changes
Tout bon pour moi, à part le problème sur url_for sur lequel je t'ai induit en erreur.

Je te laisse donc : 
- corriger le url_for
- resoudre le pylint
- rebase sur le master

En tout cas, j'approuve la PR!

2022-08-03 07:07 UTC, SnowViet commented on collectives/templates/attestation_benevole/attestation_benevole.html
> +		<img src="./collectives/templates/attestation_benevole/header_attestation_benevole.png" />
Pas de soucis :)

2022-08-03 07:17 UTC, SnowViet commented
Here you go

2022-08-04 17:34 UTC, jnguiot commented
J'ai fait le rebase: il faudra que je te montre à l'occasion ;)

2022-08-04 17:43 UTC, merged

2022-08-04 17:47 UTC, SnowViet commented
> J'ai fait le rebase: il faudra que je te montre à l'occasion ;)

J'ai essayé via VS Code, ça a pas l'air d'avoir fonctionné 😅

2022-08-04 17:52 UTC, jnguiot commented
Finalement, j'ai enlevé le footer du depôt git: ca m'embète de mettre la signature et le tampon du président toute prète à être volée sur un dépot public... Je la poserais à la main sur le serveur de production