[Feature] - Implement User Badges ( Stage 1 of Bénévoles feature)
Club-Alpin-Annecy/collectives pull request #640
Opened 2023-06-26 14:53 UTC by bbouffaut

2023-07-04 19:10 UTC, gdaviet reviewed
Merci @bbouffaut pour tout ce boulot, je n'ai parcouru les changements que rapidement mais ça me parait très bien !

Je vois que l'activity_id n'est pas NULLABLE en base, je me demande si on aurait pas intérêt à autoriser des badges sans activité liée. Par exemple, les journées de bénévolat devraient être cumulables entre activités, pareil pour les absences, etc. C'est ok de ne pas gérer cela pour la V1, mais tant qu'à faire autant éviter une future migration SQL

2023-07-04 20:12 UTC, bbouffaut commented
Hello. Merci bcp pour le feedback. Je n'ai pas tout à fait terminé.

Bon point pour le activity_id. Je vais le mettre NULLABLE, cela pourra être
utile par la suite.

A++

On Tue, Jul 4, 2023, 21:10 gdaviet ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Merci @bbouffaut <https://github.com/bbouffaut> pour tout ce boulot, je
> n'ai parcouru les changements que rapidement mais ça me parait très bien !
>
> Je vois que l'activity_id n'est pas NULLABLE en base, je me demande si on
> aurait pas intérêt à autoriser des badges sans activité liée. Par exemple,
> les journées de bénévolat devraient être cumulables entre activités, pareil
> pour les absences, etc. C'est ok de ne pas gérer cela pour la V1, mais tant
> qu'à faire autant éviter une future migration SQL
> ------------------------------
>
> In collectives/api/admin.py
> <https://github.com/Club-Alpin-Annecy/collectives/pull/640#discussion_r1252290413>
> :
>
> > +
> +    Combines a :py:class:`UserSchema` and :py:class:`.event.ActivityTypeSchema`.
> +    """
> +
> +    delete_uri = fields.Function(
> +        lambda badge: url_for("activity_supervision.remove_badge", badge_id=badge.id)
> +    )
> +    """ URI to delete this badge (WIP)
> +
> +    :type: string
> +    """
> +    user = fields.Function(lambda badge: UserSchema().dump(badge.user))
> +    """ URI to a resized version (30px) of user avatar
> +
> +    :type: string
> +    """
>
> Nit: mettre à jour les docstrings
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Club-Alpin-Annecy/collectives/pull/640#pullrequestreview-1513300558>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB32XJGZBWXEUITPCGU5IY3XORTDVANCNFSM6AAAAAAZUJEWS4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-06 09:15 UTC, bbouffaut commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Bénévoles] Implémenter le concept de Badge](https://trello.com/c/bfQNzlH1/287-b%C3%A9n%C3%A9voles-impl%C3%A9menter-le-concept-de-badge)

2023-07-08 12:41 UTC, gdaviet approved these changes
Je viens de tester rapidement, ça m'a l'air de très bien fonctionner !

Une petit remarque, dans la liste des utilisateurs du panneau admin, il y a une icone avec un lien direct pour éditer les rôles, mais pas les badges ; pour les badges il faut aller sur le profil, puis "Gérer les badges". Par cohérence ce serait bien d'avoir le même workflow pour les deux (c'est très mineur, de toutres façons a priori les badges seront principalement gérés depuis la page "gestion des activités")

2023-07-08 12:41 UTC, gdaviet commented on migrations/versions/4a5c66ab7eaa_add_badges_table.py
> +"""empty message
Ce serait bien de renseigner ce message (il apparait lorsqu'on execute "flask db upgrade")

2023-07-20 19:38 UTC, gdaviet approved these changes
Merci pour les changements, ça me paraît tout bon !

2023-09-09 16:21 UTC, jnguiot requested changes
Super commit! Merci pour le boulot. Je te laisse faire les modifications et on devrait bientôt pouvoir déployer!

2023-09-09 16:21 UTC, jnguiot commented on collectives/routes/administration.py
> +def export_badge(raw_filters=""):
Il y a un bouton pour faire l'export?

2023-09-09 16:21 UTC, jnguiot commented on collectives/routes/profile.py
> +        not current_user.has_any_role()
Le badge bénévole suffit pour avoir le certificat: on peut retirer `not current_user.has_any_role()`

2023-10-10 20:26 UTC, bbouffaut commented on collectives/api/admin.py
> +@user_is("is_supervisor", True)
OK ;-)

2023-10-10 21:09 UTC, bbouffaut commented on collectives/forms/user.py
> +        initial = kwargs.pop("initial", {})
C'est un paramètre qui permet de différencier une création de badge ou un renouvellement. On a besoin de cette info pour afficher le(s) badge(s) existants dans la Form

2023-10-10 21:58 UTC, bbouffaut commented on collectives/routes/administration.py
> +def export_badge(raw_filters=""):
Oui, sur la page "Gestion des activités": `/activity_supervision/badge`

2023-10-10 22:02 UTC, bbouffaut commented on collectives/routes/administration.py
> +def export_badge(raw_filters=""):
[Ici en fait](https://github.com/Club-Alpin-Annecy/collectives/pull/640/files#diff-7b6816c8174171786cb4d7992e3b65df7a30c515833a5d9c1c6de2f853105fa7)

2023-10-19 20:27 UTC, jnguiot commented
Yo, ton problème vient de WTForms 3.1.0... La 3.0.1 marche bien, mais le iter_choices de la 3.1.0 a un comportement différent, et je ne sais pas pourquoi. Veux-tu que je regarde, ou veux tu le faire?

2023-10-19 20:40 UTC, jnguiot commented
Pour faire simple, wtforms-components n'est plus compatible avec le dernier wtforms... et le components a l'air un peu mort...

2023-10-19 20:50 UTC, jnguiot commented
See https://github.com/kvesteri/wtforms-components/issues/76

2023-10-19 21:10 UTC, bbouffaut commented
Ah top. Merci pour le tuyau @jnguiot . Je vais m'en occuper

2023-10-22 14:04 UTC, jnguiot commented
J'ai créé https://github.com/Club-Alpin-Annecy/collectives/issues/652 pour ce problème en particulier

2023-10-22 19:09 UTC, bbouffaut commented
Aaaaaah top merci @jnguiot ton fix a fix mon pblme de tests

2023-10-22 20:26 UTC, jnguiot commented
De rien! :) j'en ai profité pour un peu de code maintenance

2023-11-03 22:31 UTC, jnguiot approved these changes

2023-11-03 22:31 UTC, merged