[FEATURE] Button Add to Calendar (Google, Apple, iCal) on event page
Club-Alpin-Annecy/collectives pull request #663
Opened 2023-11-23 14:05 UTC by o-rayer

https://trello.com/c/sASeMxfk/290-possibilit%C3%A9-dajouter-un-%C3%A9v%C3%A8nement-%C3%A0-un-calendrier-ou-download-un-fichier-ics

- Ajout d'un bouton d'ajout au calendrier, masqué quand l'event est passé. Comportement en hover et 3 options : Google, Apple, iCal
- Fichiers Poetry pour ceux qui seraient intéressés par l'utilisation
- Update de la documentation avec le setup Poetry

2023-11-30 17:55 UTC, gdaviet reviewed
Merci pour la PR !

Le bouton à l'air de bien marcher, et la position à côté de la date me parait adaptée. En revanche étant donnée la plage d'utilisateurs je suggérerais d'avoir quelque-chose d'un peu plus explicite (probablement avec un label textuel). On a déjà pas mal d'icones dans le dossier `static/img/icon/ionicon` dont une `md-calendar.svg` qui pourrait être adaptée, sinon essayer d'en trouver une dans le même style.
J'aurais aussi tendance à privilégier le onclick plutôt que le hover (surtout sur mobile, à moins que le widget gère déjà ça). 

Je ne suis pas familier avec poetry mais j'ai l'impression que le `.lock` est auto-généré, faut-il le commiter ?

2023-12-02 09:22 UTC, jnguiot requested changes
Comme expliqué, je ne souhaite pas commiter poetry tout de suite: je vais faire un revert dessus. Cependant, merci pour les calendriers: ca sera une belle addition, simple et très efficace!

2023-12-02 09:22 UTC, jnguiot commented on collectives/templates/event/event.html
> +      {% endif %}
Je pense que ce changement n'est pas lié aux calendriers :)

2023-12-02 09:22 UTC, jnguiot commented on doc/source/howto.rst
> +Method using Homebrew, Poetry & VSCode
Ce n'est pas vraiment lié aux calendriers. Si on souhaite passer sur poetry, je pense que ca doit être un commit spécifique.
Je pense que ca vaut le coup d'en parler, mais vu que je ne pense pas que ce soit sain de maintenir un requirements.txt et un poetry, il faudra qu'on fasse un choix entre les deux. Tu auras le temps pour qu'on en parle?

2023-12-02 09:24 UTC, jnguiot commented
@gdaviet Concernant le bouton, je pensais le mettre à la place de l'icone.
![image](https://github.com/Club-Alpin-Annecy/collectives/assets/45011516/e6003d53-e804-4270-b09a-d6f1cfa36d1a)

2023-12-02 09:41 UTC, jnguiot approved these changes

2023-12-02 09:42 UTC, merged

2023-12-04 19:46 UTC, o-rayer commented on doc/source/howto.rst
> +Method using Homebrew, Poetry & VSCode
Pas de problème pour moi de continuer à bosser sur mon Poetry uniquement en local et continuer d'update le requirements pour tout le monde, je ne veux surtout pas forcer la main :). Et dispo pour en parler anytime

2023-12-04 19:51 UTC, o-rayer commented
> Merci pour la PR !
> 
> Le bouton à l'air de bien marcher, et la position à côté de la date me parait adaptée. En revanche étant donnée la plage d'utilisateurs je suggérerais d'avoir quelque-chose d'un peu plus explicite (probablement avec un label textuel). On a déjà pas mal d'icones dans le dossier `static/img/icon/ionicon` dont une `md-calendar.svg` qui pourrait être adaptée, sinon essayer d'en trouver une dans le même style. J'aurais aussi tendance à privilégier le onclick plutôt que le hover (surtout sur mobile, à moins que le widget gère déjà ça).
> 
> Je ne suis pas familier avec poetry mais j'ai l'impression que le `.lock` est auto-généré, faut-il le commiter ?

@gdaviet ça n'a plus lieu d'être pour le moment mais oui, il faut commit le `.lock` même s'il est auto-généré : https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control