[FEATURE] Design for benevole management
Club-Alpin-Annecy/collectives pull request #666
Opened 2023-12-02 12:32 UTC by jnguiot

Voici mes modifications de design à propos de bénévole. 

En gros, les "badges" ne resteraient que des outils techniques: les responsables d'activités géreraient des bénévoles, des refusés,  des retardataires,  etc...

On en reparle quand vous voulez

2023-12-02 16:27 UTC, romaind8r commented
Hello,En plus de faire le point sur la roadmap,Je veux bien participer à la discussion sur la partie bénévole management car ça va être un changement majeur.______________Romain DesbrestPrésident Club Alpin Annecy +33 650 17 45 47_______________Envoyé de mon MinitelLe 2 déc. 2023 à 13:32, jnguiot ***@***.***> a écrit :﻿Voici mes modifications de design à propos de bénévole.
En gros, les "badges" ne resteraient que des outils techniques: les responsables d'activités géreraient des bénévoles, des refusés,  des retardataires,  etc...
On en reparle quand vous voulez



You can view, comment on, or merge this pull request online at:
  https://github.com/Club-Alpin-Annecy/collectives/pull/666

Commit Summary

  c63dfc9  [FEATURE] Design for benevole management


File Changes  (25 files)

  
    M
    collectives/api/admin.py
    (29)
  
  
    M
    collectives/forms/user.py
    (10)
  
  
    M
    collectives/routes/activity_supervison.py
    (163)
  
  
    M
    collectives/routes/administration.py
    (121)
  
  
    A
    collectives/static/img/icon/ionicon/receipt.svg
    (1)
  
  
    A
    collectives/static/img/icon/ionicon/refresh.svg
    (1)
  
  
    A
    collectives/static/img/icon/ionicon/thumbs-up.svg
    (1)
  
  
    M
    collectives/static/js/activity_supervision/badges_list.js
    (19)
  
  
    M
    collectives/templates/activity_supervision/activity_documents.html
    (2)
  
  
    M
    collectives/templates/activity_supervision/activity_supervision.html
    (8)
  
  
    M
    collectives/templates/activity_supervision/badges_list.html
    (37)
  
  
    M
    collectives/templates/activity_supervision/import_csv.html
    (2)
  
  
    M
    collectives/templates/activity_supervision/leaders_list.html
    (2)
  
  
    A
    collectives/templates/administration/index.html
    (26)
  
  
    A
    collectives/templates/administration/token.html
    (17)
  
  
    R
    collectives/templates/administration/user_list.html
    (16)
  
  
    M
    collectives/templates/profile.html
    (4)
  
  
    M
    collectives/utils/access.py
    (17)
  
  
    A
    collectives/utils/badges.py
    (248)
  
  
    M
    etc/cli_test_payline.py
    (1)
  
  
    A
    tests/activity/test_volunteers.py
    (93)
  
  
    M
    tests/admin/test_admin.py
    (26)
  
  
    A
    tests/admin/test_admin_badges.py
    (87)
  
  
    M
    tests/fixtures/user.py
    (2)
  
  
    M
    tests/utils.py
    (12)
  


Patch Links:

  https://github.com/Club-Alpin-Annecy/collectives/pull/666.patch
  https://github.com/Club-Alpin-Annecy/collectives/pull/666.diff


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-12-02 18:59 UTC, gdaviet requested changes
Ca me semble effectivement une interface plus simple pour laisser les responsables d'activité se familiariser avec le concept.

Pour l'instant la question ne se pose pas car on n'a pas d'autres badges, mais je ne suis pas sur de voir la raison de laisser la hotline plutot que les responsables d'activité ajouter des badges génériques. Enfin vu que tout est maintenant dans utils, ca sera facile de d'ajouter ca à l'interface de supervision si jamais on en a besoin.

Merci d'avoir nettoyé la page d'admin, à terme ce serait bien d'extraire la gestion des roles comme tu l'as fait pour les badges. Mais bon pour une autre fois, rien de pressant.

Je laisse Romain commenter pour les termes employés, mais ce sera peut-être plus facile une foid déployé sur test.collectives

Change requested pour les urls en dur, je préfère vraiment qu'on s'en tienne à `url_for`

2023-12-02 18:59 UTC, gdaviet commented on collectives/api/admin.py
> +    delete_uri = fields.Function(lambda badge: f"./delete/{badge.id}")
J'ai peur que ce genre de construction soit difficilement maintenable. Il serait préférable de passer le blueprint en argument et d'utiliser un `url_for` classique

2023-12-02 18:59 UTC, gdaviet commented on collectives/forms/user.py
>          """Overloaded constructor populating activity list"""
Pour plus de clarté ce serait bien de documenter les arguments kwargs acceptés/requis

2023-12-02 18:59 UTC, gdaviet commented on collectives/templates/activity_supervision/badges_list.html
> +      <form action="./add" id="user-search-form" method="POST" >
Idem, il faudrait garder le `url_for`. On peut utiliser un num de router commencant par `.` pour désigner la blueprint courante

2023-12-02 18:59 UTC, gdaviet commented on collectives/templates/profile.html
> +    <h4 class="heading-4">Notes</h4>
"Notes" me paraît un peu étrange comme formulation. Soit on laisse quelque chose de générique et on garde "Badge", soit on fait quelque chose de spécifique pour Bénévole et dans ce cas pas besoin du heading

2023-12-03 19:18 UTC, jnguiot commented
>  Je laisse Romain commenter pour les termes employés, mais ce sera peut-être plus facile une fois déployé sur test.collectives
En effet, je pense que c'est le mieux

2023-12-08 23:54 UTC, jnguiot commented on collectives/templates/activity_supervision/badges_list.html
> +      <form action="./add" id="user-search-form" method="POST" >
J'ai créé la variable `routes` pour éviter les trucs bizarres comme ça

2023-12-20 20:25 UTC, gdaviet approved these changes

2023-12-20 20:25 UTC, merged